language: python

os:
  - linux

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python -m pytest papis tests --cov=papis

install:
  - pip install setuptools
  - pip install python-coveralls
  - pip install -e .[develop]
  - pip install -e .[optional]
  - make submodules
  - make install

after_success:
  - coveralls
